In [1]:
import torch
print(torch.__version__)

2.13.0+cpu


In [2]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"using GPU : {torch.cuda.get_device_name(0)}")    
else:
    print("GPU is not available")

GPU is not available


### Creating a Tensor

In [5]:
# using empty : It only allocate memory of the given size
a = torch.empty(2,3)
a

tensor([[1.6746e+35, 2.1132e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [6]:
# check data type
type(a)

torch.Tensor

In [8]:
# all ele of tensors are zero
torch.zeros(5)

tensor([0., 0., 0., 0., 0.])

In [9]:
torch.ones(10)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
# using rand
torch.rand(2,3)

tensor([[0.0267, 0.7544, 0.0032],
        [0.4899, 0.9832, 0.0993]])

In [11]:
# use of seed -> This seed will generate the output every times
torch.manual_seed(5)
torch.rand(2,3)

tensor([[0.8303, 0.1261, 0.9075],
        [0.8199, 0.9201, 0.1166]])

In [12]:
torch.manual_seed(5)
torch.rand(2,3)

tensor([[0.8303, 0.1261, 0.9075],
        [0.8199, 0.9201, 0.1166]])

In [17]:
# using tensor
a = torch.tensor([[1,2,3],[4,5,6]])

In [18]:
type(a)

torch.Tensor

In [22]:
torch.arange(0,10,3)

tensor([0, 3, 6, 9])

In [23]:
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [25]:
# Identity matrix
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [27]:
torch.full((5,5),9)

tensor([[9, 9, 9, 9, 9],
        [9, 9, 9, 9, 9],
        [9, 9, 9, 9, 9],
        [9, 9, 9, 9, 9],
        [9, 9, 9, 9, 9]])

In [28]:
a.shape

torch.Size([2, 3])

### Tensor Data type

In [29]:
# we can change the datatype of the tensor according to our need
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [32]:
# Mathematical operations
x = torch.rand(2,2)
x

tensor([[0.6064, 0.5646],
        [0.0724, 0.6593]])

In [33]:
x+2

tensor([[2.6064, 2.5646],
        [2.0724, 2.6593]])